name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: setan
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: |
        TAG=$(date +date "+%Y%m%d")
        docker build . --file Dockerfile --tag vr1090/simple_fetch:$TAG
        docker images
        echo " dalem build $TAG"
        docker push vr1090/simple_fetch:$TAG
