name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: setan
    steps:
    - name: test env
      run: echo "hello world $koplak ${{ env.hello }} atau ${{env.HELLO}} $kutu gila value $gila ${{ vars.HI}} atau kecil ${{ vars.hi}} emang ada?"
