name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: test env
      env:
        koplak: ${{ secrets }}
      run: echo "hello world ${{ secrets}} emang ada?"